#!/usr/bin/env bash

##################################################################
set -e -o pipefail

##################################################################
# Create custom dictionary with special tokens
DICT_FILE="${SOCMEDIA_LSRC}/dict/special_tokens.lex"
if ! test -f "${DICT_FILE}" -a -r "${DICT_FILE}"; then
    echo "Dictionary file '${DICT_FILE}' can not be loaded" >&2
    exit 1
fi
temp_dict="socmedia.$$.dic"
trap 'rm -f ${temp_dict};' ERR EXIT

# populate temporary dict
egrep '.' "${DICT_FILE}" | wc -l | cut -f1 -d' ' > "${temp_dict}"
cut -f1 -d '	' -- "${DICT_FILE}" | awk 'NF{sub(/^%/, ""); print}' >> "${temp_dict}"

##################################################################
# run input files through hunspell
awk 'NF{print "^" $0}' $@ | \
    LC_ALL=C.UTF-8 hunspell -a -d de_CH,"$(basename ${temp_dict%%.dic})" \
    -i UTF-8 -p "$(dirname {temp_dict})" -w | \
    awk 'NF && ($1 == "#" || $1 == "&") {print $2}' | \
    LC_ALL=C.UTF-8 sort -d
