#!/usr/bin/awk -f

##################################################################
function annotate(istring) {
    istring = gensub(/((@|[MR]T[[:blank:]]+)[^[:blank:]]+)/,			\
		     "<attoken class=\"true_pos\">\\1</attoken>", "g", istring)
    istring = gensub(/(#[^[:blank:]]+)/,				\
		     "<hashtag class=\"true_pos\">\\1</hashtag>", "g", istring)
    istring = gensub(/((http|www)[^[:blank:]]*)/, "<link class=\"true_pos\">\\1</link>", \
		     "g", istring)
    istring = gensub(/(:-[()])/, "<smiley class=\"true_pos\">\\1</smiley>", \
		     "g", istring)
    return istring
}

##################################################################
BEGIN {
    print "<difference>"
}

##################################################################
NF && /\t/ {
    if (split($0, arr, /\t/) > 2) {
	print "Incorrect line format: \x27" $0 "\x27" > "/dev/stderr";
	exit 1
    }
    print annotate(arr[1])
    print arr[2] "\n"
}

##################################################################
END {
    print "</difference>"
}
